/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ChaptersIndexRouteImport } from './routes/chapters.index'
import { Route as ChaptersSlugRouteImport } from './routes/chapters.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersSlugRoute = ChaptersSlugRouteImport.update({
  id: '/chapters/$slug',
  path: '/chapters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/outreach': typeof OutreachRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/outreach': typeof OutreachRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters': typeof ChaptersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conclusion': typeof ConclusionRoute
  '/outreach': typeof OutreachRoute
  '/timeline': typeof TimelineRoute
  '/chapters/$slug': typeof ChaptersSlugRoute
  '/chapters/': typeof ChaptersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conclusion'
    | '/outreach'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conclusion'
    | '/outreach'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters'
  id:
    | '__root__'
    | '/'
    | '/conclusion'
    | '/outreach'
    | '/timeline'
    | '/chapters/$slug'
    | '/chapters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConclusionRoute: typeof ConclusionRoute
  OutreachRoute: typeof OutreachRoute
  TimelineRoute: typeof TimelineRoute
  ChaptersSlugRoute: typeof ChaptersSlugRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$slug': {
      id: '/chapters/$slug'
      path: '/chapters/$slug'
      fullPath: '/chapters/$slug'
      preLoaderRoute: typeof ChaptersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConclusionRoute: ConclusionRoute,
  OutreachRoute: OutreachRoute,
  TimelineRoute: TimelineRoute,
  ChaptersSlugRoute: ChaptersSlugRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
